name: images
on:
  schedule:
  - cron: "31 2 * * 2"
  push:
    branches:
    - master
jobs:
  build-ubuntu-1604:
    env:
      VERSION: "16.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build 
      run: docker build --pull --build-arg VERSION=$VERSION -f ubuntu-systemd.dockerfile -t golovanovsv/ubuntu:$VERSION-systemd .
  build-ubuntu-1804:
    env:
      VERSION: "18.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build 
      run: docker build --pull --build-arg VERSION=$VERSION -f ubuntu-systemd.dockerfile -t golovanovsv/ubuntu:$VERSION-systemd .
  login:
    needs:
    - "build-ubuntu-1604"
    - "build-ubuntu-1804"
    runs-on: ubuntu-latest
    steps:
    - name: login to docker hub
      run: echo "${{ secrets.DHUB_TOKEN }}" | docker login -u ${{ secrets.DHUB_USERNAME }} --password-stdin
  push-ubuntu-1604:
    env:
      VERSION: "16.04"
    needs:
    - "login"
    runs-on: ubuntu-latest
    steps:
    - name: push
      run: docker push golovanovsv/ubuntu:$VERSION-systemd
  push-ubuntu-1804:
    env:
      VERSION: "18.04"
    needs:
    - "login"
    runs-on: ubuntu-latest
    steps:
    - name: push
      run: docker push golovanovsv/ubuntu:$VERSION-systemd
